s/&Aacute;/Á/g
s/&Aacute/Á/g
s/&aacute;/á/g
s/&aacute/á/g
s/&Abreve;/Ă/g
s/&abreve;/ă/g
s/&ac;/∾/g
s/&acd;/∿/g
s/&acE;/∾̳/g
s/&Acirc;/Â/g
s/&Acirc/Â/g
s/&acirc;/â/g
s/&acirc/â/g
s/&acute;/´/g
s/&acute/´/g
s/&Acy;/А/g
s/&acy;/а/g
s/&AElig;/Æ/g
s/&AElig/Æ/g
s/&aelig;/æ/g
s/&aelig/æ/g
s/&af;/⁡/g
s/&Agrave;/À/g
s/&Agrave/À/g
s/&agrave;/à/g
s/&agrave/à/g
s/&alefsym;/ℵ/g
s/&aleph;/ℵ/g
s/&Alpha;/Α/g
s/&alpha;/α/g
s/&Amacr;/Ā/g
s/&amacr;/ā/g
s/&amalg;/⨿/g
s/&AMP;/\&/g
s/&AMP/\&/g
s/&amp;/\&/g
s/&amp/\&/g
s/&And;/⩓/g
s/&and;/∧/g
s/&andand;/⩕/g
s/&andd;/⩜/g
s/&andslope;/⩘/g
s/&andv;/⩚/g
s/&ang;/∠/g
s/&ange;/⦤/g
s/&angle;/∠/g
s/&angmsd;/∡/g
s/&angmsdaa;/⦨/g
s/&angmsdab;/⦩/g
s/&angmsdac;/⦪/g
s/&angmsdad;/⦫/g
s/&angmsdae;/⦬/g
s/&angmsdaf;/⦭/g
s/&angmsdag;/⦮/g
s/&angmsdah;/⦯/g
s/&angrt;/∟/g
s/&angrtvb;/⊾/g
s/&angrtvbd;/⦝/g
s/&angsph;/∢/g
s/&angst;/Å/g
s/&angzarr;/⍼/g
s/&Aogon;/Ą/g
s/&aogon;/ą/g
s/&ap;/≈/g
s/&apacir;/⩯/g
s/&apE;/⩰/g
s/&ape;/≊/g
s/&apid;/≋/g
s/&apos;/'/g
s/&ApplyFunction;/⁡/g
s/&approx;/≈/g
s/&approxeq;/≊/g
s/&Aring;/Å/g
s/&Aring/Å/g
s/&aring;/å/g
s/&aring/å/g
s/&Assign;/≔/g
s/&ast;/*/g
s/&asymp;/≈/g
s/&asympeq;/≍/g
s/&Atilde;/Ã/g
s/&Atilde/Ã/g
s/&atilde;/ã/g
s/&atilde/ã/g
s/&Auml;/Ä/g
s/&Auml/Ä/g
s/&auml;/ä/g
s/&auml/ä/g
s/&awconint;/∳/g
s/&awint;/⨑/g
s/&backcong;/≌/g
s/&backepsilon;/϶/g
s/&backprime;/‵/g
s/&backsim;/∽/g
s/&backsimeq;/⋍/g
s/&Backslash;/∖/g
s/&Barv;/⫧/g
s/&barvee;/⊽/g
s/&Barwed;/⌆/g
s/&barwed;/⌅/g
s/&barwedge;/⌅/g
s/&bbrk;/⎵/g
s/&bbrktbrk;/⎶/g
s/&bcong;/≌/g
s/&Bcy;/Б/g
s/&bcy;/б/g
s/&bdquo;/„/g
s/&becaus;/∵/g
s/&Because;/∵/g
s/&because;/∵/g
s/&bemptyv;/⦰/g
s/&bepsi;/϶/g
s/&bernou;/ℬ/g
s/&Bernoullis;/ℬ/g
s/&Beta;/Β/g
s/&beta;/β/g
s/&beth;/ℶ/g
s/&between;/≬/g
s/&bigcap;/⋂/g
s/&bigcirc;/◯/g
s/&bigcup;/⋃/g
s/&bigodot;/⨀/g
s/&bigoplus;/⨁/g
s/&bigotimes;/⨂/g
s/&bigsqcup;/⨆/g
s/&bigstar;/★/g
s/&bigtriangledown;/▽/g
s/&bigtriangleup;/△/g
s/&biguplus;/⨄/g
s/&bigvee;/⋁/g
s/&bigwedge;/⋀/g
s/&bkarow;/⤍/g
s/&blacklozenge;/⧫/g
s/&blacksquare;/▪/g
s/&blacktriangle;/▴/g
s/&blacktriangledown;/▾/g
s/&blacktriangleleft;/◂/g
s/&blacktriangleright;/▸/g
s/&blank;/␣/g
s/&blk12;/▒/g
s/&blk14;/░/g
s/&blk34;/▓/g
s/&block;/█/g
s/&bne;/=⃥/g
s/&bnequiv;/≡⃥/g
s/&bNot;/⫭/g
s/&bnot;/⌐/g
s/&bot;/⊥/g
s/&bottom;/⊥/g
s/&bowtie;/⋈/g
s/&boxbox;/⧉/g
s/&boxDL;/╗/g
s/&boxDl;/╖/g
s/&boxdL;/╕/g
s/&boxdl;/┐/g
s/&boxDR;/╔/g
s/&boxDr;/╓/g
s/&boxdR;/╒/g
s/&boxdr;/┌/g
s/&boxH;/═/g
s/&boxh;/─/g
s/&boxHD;/╦/g
s/&boxHd;/╤/g
s/&boxhD;/╥/g
s/&boxhd;/┬/g
s/&boxHU;/╩/g
s/&boxHu;/╧/g
s/&boxhU;/╨/g
s/&boxhu;/┴/g
s/&boxminus;/⊟/g
s/&boxplus;/⊞/g
s/&boxtimes;/⊠/g
s/&boxUL;/╝/g
s/&boxUl;/╜/g
s/&boxuL;/╛/g
s/&boxul;/┘/g
s/&boxUR;/╚/g
s/&boxUr;/╙/g
s/&boxuR;/╘/g
s/&boxur;/└/g
s/&boxV;/║/g
s/&boxv;/│/g
s/&boxVH;/╬/g
s/&boxVh;/╫/g
s/&boxvH;/╪/g
s/&boxvh;/┼/g
s/&boxVL;/╣/g
s/&boxVl;/╢/g
s/&boxvL;/╡/g
s/&boxvl;/┤/g
s/&boxVR;/╠/g
s/&boxVr;/╟/g
s/&boxvR;/╞/g
s/&boxvr;/├/g
s/&bprime;/‵/g
s/&Breve;/˘/g
s/&breve;/˘/g
s/&brvbar;/¦/g
s/&brvbar/¦/g
s/&Bscr;/ℬ/g
s/&bsemi;/⁏/g
s/&bsim;/∽/g
s/&bsime;/⋍/g
s/&bsol;/\\/g
s/&bsolb;/⧅/g
s/&bsolhsub;/⟈/g
s/&bull;/•/g
s/&bullet;/•/g
s/&bump;/≎/g
s/&bumpE;/⪮/g
s/&bumpe;/≏/g
s/&Bumpeq;/≎/g
s/&bumpeq;/≏/g
s/&Cacute;/Ć/g
s/&cacute;/ć/g
s/&Cap;/⋒/g
s/&cap;/∩/g
s/&capand;/⩄/g
s/&capbrcup;/⩉/g
s/&capcap;/⩋/g
s/&capcup;/⩇/g
s/&capdot;/⩀/g
s/&CapitalDifferentialD;/ⅅ/g
s/&caps;/∩︀/g
s/&caret;/⁁/g
s/&caron;/ˇ/g
s/&Cayleys;/ℭ/g
s/&ccaps;/⩍/g
s/&Ccaron;/Č/g
s/&ccaron;/č/g
s/&Ccedil;/Ç/g
s/&Ccedil/Ç/g
s/&ccedil;/ç/g
s/&ccedil/ç/g
s/&Ccirc;/Ĉ/g
s/&ccirc;/ĉ/g
s/&Cconint;/∰/g
s/&ccups;/⩌/g
s/&ccupssm;/⩐/g
s/&Cdot;/Ċ/g
s/&cdot;/ċ/g
s/&cedil;/¸/g
s/&cedil/¸/g
s/&Cedilla;/¸/g
s/&cemptyv;/⦲/g
s/&cent;/¢/g
s/&cent/¢/g
s/&CenterDot;/·/g
s/&centerdot;/·/g
s/&Cfr;/ℭ/g
s/&CHcy;/Ч/g
s/&chcy;/ч/g
s/&check;/✓/g
s/&checkmark;/✓/g
s/&Chi;/Χ/g
s/&chi;/χ/g
s/&cir;/○/g
s/&circ;/ˆ/g
s/&circeq;/≗/g
s/&circlearrowleft;/↺/g
s/&circlearrowright;/↻/g
s/&circledast;/⊛/g
s/&circledcirc;/⊚/g
s/&circleddash;/⊝/g
s/&CircleDot;/⊙/g
s/&circledR;/®/g
s/&circledS;/Ⓢ/g
s/&CircleMinus;/⊖/g
s/&CirclePlus;/⊕/g
s/&CircleTimes;/⊗/g
s/&cirE;/⧃/g
s/&cire;/≗/g
s/&cirfnint;/⨐/g
s/&cirmid;/⫯/g
s/&cirscir;/⧂/g
s/&ClockwiseContourIntegral;/∲/g
s/&CloseCurlyDoubleQuote;/”/g
s/&CloseCurlyQuote;/’/g
s/&clubs;/♣/g
s/&clubsuit;/♣/g
s/&Colon;/∷/g
s/&colon;/:/g
s/&Colone;/⩴/g
s/&colone;/≔/g
s/&coloneq;/≔/g
s/&comma;/,/g
s/&commat;/@/g
s/&comp;/∁/g
s/&compfn;/∘/g
s/&complement;/∁/g
s/&complexes;/ℂ/g
s/&cong;/≅/g
s/&congdot;/⩭/g
s/&Congruent;/≡/g
s/&Conint;/∯/g
s/&conint;/∮/g
s/&ContourIntegral;/∮/g
s/&Copf;/ℂ/g
s/&coprod;/∐/g
s/&Coproduct;/∐/g
s/&COPY;/©/g
s/&COPY/©/g
s/&copy;/©/g
s/&copy/©/g
s/&copysr;/℗/g
s/&CounterClockwiseContourIntegral;/∳/g
s/&crarr;/↵/g
s/&Cross;/⨯/g
s/&cross;/✗/g
s/&csub;/⫏/g
s/&csube;/⫑/g
s/&csup;/⫐/g
s/&csupe;/⫒/g
s/&ctdot;/⋯/g
s/&cudarrl;/⤸/g
s/&cudarrr;/⤵/g
s/&cuepr;/⋞/g
s/&cuesc;/⋟/g
s/&cularr;/↶/g
s/&cularrp;/⤽/g
s/&Cup;/⋓/g
s/&cup;/∪/g
s/&cupbrcap;/⩈/g
s/&CupCap;/≍/g
s/&cupcap;/⩆/g
s/&cupcup;/⩊/g
s/&cupdot;/⊍/g
s/&cupor;/⩅/g
s/&cups;/∪︀/g
s/&curarr;/↷/g
s/&curarrm;/⤼/g
s/&curlyeqprec;/⋞/g
s/&curlyeqsucc;/⋟/g
s/&curlyvee;/⋎/g
s/&curlywedge;/⋏/g
s/&curren;/¤/g
s/&curren/¤/g
s/&curvearrowleft;/↶/g
s/&curvearrowright;/↷/g
s/&cuvee;/⋎/g
s/&cuwed;/⋏/g
s/&cwconint;/∲/g
s/&cwint;/∱/g
s/&cylcty;/⌭/g
s/&Dagger;/‡/g
s/&dagger;/†/g
s/&daleth;/ℸ/g
s/&Darr;/↡/g
s/&dArr;/⇓/g
s/&darr;/↓/g
s/&dash;/‐/g
s/&Dashv;/⫤/g
s/&dashv;/⊣/g
s/&dbkarow;/⤏/g
s/&dblac;/˝/g
s/&Dcaron;/Ď/g
s/&dcaron;/ď/g
s/&Dcy;/Д/g
s/&dcy;/д/g
s/&DD;/ⅅ/g
s/&dd;/ⅆ/g
s/&ddagger;/‡/g
s/&ddarr;/⇊/g
s/&DDotrahd;/⤑/g
s/&ddotseq;/⩷/g
s/&deg;/°/g
s/&deg/°/g
s/&Del;/∇/g
s/&Delta;/Δ/g
s/&delta;/δ/g
s/&demptyv;/⦱/g
s/&dfisht;/⥿/g
s/&dHar;/⥥/g
s/&dharl;/⇃/g
s/&dharr;/⇂/g
s/&DiacriticalAcute;/´/g
s/&DiacriticalDot;/˙/g
s/&DiacriticalDoubleAcute;/˝/g
s/&DiacriticalGrave;/`/g
s/&DiacriticalTilde;/˜/g
s/&diam;/⋄/g
s/&Diamond;/⋄/g
s/&diamond;/⋄/g
s/&diamondsuit;/♦/g
s/&diams;/♦/g
s/&die;/¨/g
s/&DifferentialD;/ⅆ/g
s/&digamma;/ϝ/g
s/&disin;/⋲/g
s/&div;/÷/g
s/&divide;/÷/g
s/&divide/÷/g
s/&divideontimes;/⋇/g
s/&divonx;/⋇/g
s/&DJcy;/Ђ/g
s/&djcy;/ђ/g
s/&dlcorn;/⌞/g
s/&dlcrop;/⌍/g
s/&dollar;/$/g
s/&Dot;/¨/g
s/&dot;/˙/g
s/&DotDot;/⃜/g
s/&doteq;/≐/g
s/&doteqdot;/≑/g
s/&DotEqual;/≐/g
s/&dotminus;/∸/g
s/&dotplus;/∔/g
s/&dotsquare;/⊡/g
s/&doublebarwedge;/⌆/g
s/&DoubleContourIntegral;/∯/g
s/&DoubleDot;/¨/g
s/&DoubleDownArrow;/⇓/g
s/&DoubleLeftArrow;/⇐/g
s/&DoubleLeftRightArrow;/⇔/g
s/&DoubleLeftTee;/⫤/g
s/&DoubleLongLeftArrow;/⟸/g
s/&DoubleLongLeftRightArrow;/⟺/g
s/&DoubleLongRightArrow;/⟹/g
s/&DoubleRightArrow;/⇒/g
s/&DoubleRightTee;/⊨/g
s/&DoubleUpArrow;/⇑/g
s/&DoubleUpDownArrow;/⇕/g
s/&DoubleVerticalBar;/∥/g
s/&DownArrow;/↓/g
s/&Downarrow;/⇓/g
s/&downarrow;/↓/g
s/&DownArrowBar;/⤓/g
s/&DownArrowUpArrow;/⇵/g
s/&DownBreve;/̑/g
s/&downdownarrows;/⇊/g
s/&downharpoonleft;/⇃/g
s/&downharpoonright;/⇂/g
s/&DownLeftRightVector;/⥐/g
s/&DownLeftTeeVector;/⥞/g
s/&DownLeftVector;/↽/g
s/&DownLeftVectorBar;/⥖/g
s/&DownRightTeeVector;/⥟/g
s/&DownRightVector;/⇁/g
s/&DownRightVectorBar;/⥗/g
s/&DownTee;/⊤/g
s/&DownTeeArrow;/↧/g
s/&drbkarow;/⤐/g
s/&drcorn;/⌟/g
s/&drcrop;/⌌/g
s/&DScy;/Ѕ/g
s/&dscy;/ѕ/g
s/&dsol;/⧶/g
s/&Dstrok;/Đ/g
s/&dstrok;/đ/g
s/&dtdot;/⋱/g
s/&dtri;/▿/g
s/&dtrif;/▾/g
s/&duarr;/⇵/g
s/&duhar;/⥯/g
s/&dwangle;/⦦/g
s/&DZcy;/Џ/g
s/&dzcy;/џ/g
s/&dzigrarr;/⟿/g
s/&Eacute;/É/g
s/&Eacute/É/g
s/&eacute;/é/g
s/&eacute/é/g
s/&easter;/⩮/g
s/&Ecaron;/Ě/g
s/&ecaron;/ě/g
s/&ecir;/≖/g
s/&Ecirc;/Ê/g
s/&Ecirc/Ê/g
s/&ecirc;/ê/g
s/&ecirc/ê/g
s/&ecolon;/≕/g
s/&Ecy;/Э/g
s/&ecy;/э/g
s/&eDDot;/⩷/g
s/&Edot;/Ė/g
s/&eDot;/≑/g
s/&edot;/ė/g
s/&ee;/ⅇ/g
s/&efDot;/≒/g
s/&eg;/⪚/g
s/&Egrave;/È/g
s/&Egrave/È/g
s/&egrave;/è/g
s/&egrave/è/g
s/&egs;/⪖/g
s/&egsdot;/⪘/g
s/&el;/⪙/g
s/&Element;/∈/g
s/&elinters;/⏧/g
s/&ell;/ℓ/g
s/&els;/⪕/g
s/&elsdot;/⪗/g
s/&Emacr;/Ē/g
s/&emacr;/ē/g
s/&empty;/∅/g
s/&emptyset;/∅/g
s/&EmptySmallSquare;/◻/g
s/&emptyv;/∅/g
s/&EmptyVerySmallSquare;/▫/g
s/&emsp;/ /g
s/&emsp13;/ /g
s/&emsp14;/ /g
s/&ENG;/Ŋ/g
s/&eng;/ŋ/g
s/&ensp;/ /g
s/&Eogon;/Ę/g
s/&eogon;/ę/g
s/&epar;/⋕/g
s/&eparsl;/⧣/g
s/&eplus;/⩱/g
s/&epsi;/ε/g
s/&Epsilon;/Ε/g
s/&epsilon;/ε/g
s/&epsiv;/ϵ/g
s/&eqcirc;/≖/g
s/&eqcolon;/≕/g
s/&eqsim;/≂/g
s/&eqslantgtr;/⪖/g
s/&eqslantless;/⪕/g
s/&Equal;/⩵/g
s/&equals;/=/g
s/&EqualTilde;/≂/g
s/&equest;/≟/g
s/&Equilibrium;/⇌/g
s/&equiv;/≡/g
s/&equivDD;/⩸/g
s/&eqvparsl;/⧥/g
s/&erarr;/⥱/g
s/&erDot;/≓/g
s/&Escr;/ℰ/g
s/&escr;/ℯ/g
s/&esdot;/≐/g
s/&Esim;/⩳/g
s/&esim;/≂/g
s/&Eta;/Η/g
s/&eta;/η/g
s/&ETH;/Ð/g
s/&ETH/Ð/g
s/&eth;/ð/g
s/&eth/ð/g
s/&Euml;/Ë/g
s/&Euml/Ë/g
s/&euml;/ë/g
s/&euml/ë/g
s/&euro;/€/g
s/&excl;/!/g
s/&exist;/∃/g
s/&Exists;/∃/g
s/&expectation;/ℰ/g
s/&ExponentialE;/ⅇ/g
s/&exponentiale;/ⅇ/g
s/&fallingdotseq;/≒/g
s/&Fcy;/Ф/g
s/&fcy;/ф/g
s/&female;/♀/g
s/&ffilig;/ﬃ/g
s/&fflig;/ﬀ/g
s/&ffllig;/ﬄ/g
s/&filig;/ﬁ/g
s/&FilledSmallSquare;/◼/g
s/&FilledVerySmallSquare;/▪/g
s/&fjlig;/fj/g
s/&flat;/♭/g
s/&fllig;/ﬂ/g
s/&fltns;/▱/g
s/&fnof;/ƒ/g
s/&ForAll;/∀/g
s/&forall;/∀/g
s/&fork;/⋔/g
s/&forkv;/⫙/g
s/&Fouriertrf;/ℱ/g
s/&fpartint;/⨍/g
s/&frac12;/½/g
s/&frac12/½/g
s/&frac13;/⅓/g
s/&frac14;/¼/g
s/&frac14/¼/g
s/&frac15;/⅕/g
s/&frac16;/⅙/g
s/&frac18;/⅛/g
s/&frac23;/⅔/g
s/&frac25;/⅖/g
s/&frac34;/¾/g
s/&frac34/¾/g
s/&frac35;/⅗/g
s/&frac38;/⅜/g
s/&frac45;/⅘/g
s/&frac56;/⅚/g
s/&frac58;/⅝/g
s/&frac78;/⅞/g
s/&frasl;/⁄/g
s/&frown;/⌢/g
s/&Fscr;/ℱ/g
s/&gacute;/ǵ/g
s/&Gamma;/Γ/g
s/&gamma;/γ/g
s/&Gammad;/Ϝ/g
s/&gammad;/ϝ/g
s/&gap;/⪆/g
s/&Gbreve;/Ğ/g
s/&gbreve;/ğ/g
s/&Gcedil;/Ģ/g
s/&Gcirc;/Ĝ/g
s/&gcirc;/ĝ/g
s/&Gcy;/Г/g
s/&gcy;/г/g
s/&Gdot;/Ġ/g
s/&gdot;/ġ/g
s/&gE;/≧/g
s/&ge;/≥/g
s/&gEl;/⪌/g
s/&gel;/⋛/g
s/&geq;/≥/g
s/&geqq;/≧/g
s/&geqslant;/⩾/g
s/&ges;/⩾/g
s/&gescc;/⪩/g
s/&gesdot;/⪀/g
s/&gesdoto;/⪂/g
s/&gesdotol;/⪄/g
s/&gesl;/⋛︀/g
s/&gesles;/⪔/g
s/&Gg;/⋙/g
s/&gg;/≫/g
s/&ggg;/⋙/g
s/&gimel;/ℷ/g
s/&GJcy;/Ѓ/g
s/&gjcy;/ѓ/g
s/&gl;/≷/g
s/&gla;/⪥/g
s/&glE;/⪒/g
s/&glj;/⪤/g
s/&gnap;/⪊/g
s/&gnapprox;/⪊/g
s/&gnE;/≩/g
s/&gne;/⪈/g
s/&gneq;/⪈/g
s/&gneqq;/≩/g
s/&gnsim;/⋧/g
s/&grave;/`/g
s/&GreaterEqual;/≥/g
s/&GreaterEqualLess;/⋛/g
s/&GreaterFullEqual;/≧/g
s/&GreaterGreater;/⪢/g
s/&GreaterLess;/≷/g
s/&GreaterSlantEqual;/⩾/g
s/&GreaterTilde;/≳/g
s/&gscr;/ℊ/g
s/&gsim;/≳/g
s/&gsime;/⪎/g
s/&gsiml;/⪐/g
s/&GT;/>/g
s/&GT/>/g
s/&Gt;/≫/g
s/&gt;/>/g
s/&gt/>/g
s/&gtcc;/⪧/g
s/&gtcir;/⩺/g
s/&gtdot;/⋗/g
s/&gtlPar;/⦕/g
s/&gtquest;/⩼/g
s/&gtrapprox;/⪆/g
s/&gtrarr;/⥸/g
s/&gtrdot;/⋗/g
s/&gtreqless;/⋛/g
s/&gtreqqless;/⪌/g
s/&gtrless;/≷/g
s/&gtrsim;/≳/g
s/&gvertneqq;/≩︀/g
s/&gvnE;/≩︀/g
s/&Hacek;/ˇ/g
s/&hairsp;/ /g
s/&half;/½/g
s/&hamilt;/ℋ/g
s/&HARDcy;/Ъ/g
s/&hardcy;/ъ/g
s/&hArr;/⇔/g
s/&harr;/↔/g
s/&harrcir;/⥈/g
s/&harrw;/↭/g
s/&Hat;/^/g
s/&hbar;/ℏ/g
s/&Hcirc;/Ĥ/g
s/&hcirc;/ĥ/g
s/&hearts;/♥/g
s/&heartsuit;/♥/g
s/&hellip;/…/g
s/&hercon;/⊹/g
s/&Hfr;/ℌ/g
s/&HilbertSpace;/ℋ/g
s/&hksearow;/⤥/g
s/&hkswarow;/⤦/g
s/&hoarr;/⇿/g
s/&homtht;/∻/g
s/&hookleftarrow;/↩/g
s/&hookrightarrow;/↪/g
s/&Hopf;/ℍ/g
s/&horbar;/―/g
s/&HorizontalLine;/─/g
s/&Hscr;/ℋ/g
s/&hslash;/ℏ/g
s/&Hstrok;/Ħ/g
s/&hstrok;/ħ/g
s/&HumpDownHump;/≎/g
s/&HumpEqual;/≏/g
s/&hybull;/⁃/g
s/&hyphen;/‐/g
s/&Iacute;/Í/g
s/&Iacute/Í/g
s/&iacute;/í/g
s/&iacute/í/g
s/&ic;/⁣/g
s/&Icirc;/Î/g
s/&Icirc/Î/g
s/&icirc;/î/g
s/&icirc/î/g
s/&Icy;/И/g
s/&icy;/и/g
s/&Idot;/İ/g
s/&IEcy;/Е/g
s/&iecy;/е/g
s/&iexcl;/¡/g
s/&iexcl/¡/g
s/&iff;/⇔/g
s/&Ifr;/ℑ/g
s/&Igrave;/Ì/g
s/&Igrave/Ì/g
s/&igrave;/ì/g
s/&igrave/ì/g
s/&ii;/ⅈ/g
s/&iiiint;/⨌/g
s/&iiint;/∭/g
s/&iinfin;/⧜/g
s/&iiota;/℩/g
s/&IJlig;/Ĳ/g
s/&ijlig;/ĳ/g
s/&Im;/ℑ/g
s/&Imacr;/Ī/g
s/&imacr;/ī/g
s/&image;/ℑ/g
s/&ImaginaryI;/ⅈ/g
s/&imagline;/ℐ/g
s/&imagpart;/ℑ/g
s/&imath;/ı/g
s/&imof;/⊷/g
s/&imped;/Ƶ/g
s/&Implies;/⇒/g
s/&in;/∈/g
s/&incare;/℅/g
s/&infin;/∞/g
s/&infintie;/⧝/g
s/&inodot;/ı/g
s/&Int;/∬/g
s/&int;/∫/g
s/&intcal;/⊺/g
s/&integers;/ℤ/g
s/&Integral;/∫/g
s/&intercal;/⊺/g
s/&Intersection;/⋂/g
s/&intlarhk;/⨗/g
s/&intprod;/⨼/g
s/&InvisibleComma;/⁣/g
s/&InvisibleTimes;/⁢/g
s/&IOcy;/Ё/g
s/&iocy;/ё/g
s/&Iogon;/Į/g
s/&iogon;/į/g
s/&Iota;/Ι/g
s/&iota;/ι/g
s/&iprod;/⨼/g
s/&iquest;/¿/g
s/&iquest/¿/g
s/&Iscr;/ℐ/g
s/&isin;/∈/g
s/&isindot;/⋵/g
s/&isinE;/⋹/g
s/&isins;/⋴/g
s/&isinsv;/⋳/g
s/&isinv;/∈/g
s/&it;/⁢/g
s/&Itilde;/Ĩ/g
s/&itilde;/ĩ/g
s/&Iukcy;/І/g
s/&iukcy;/і/g
s/&Iuml;/Ï/g
s/&Iuml/Ï/g
s/&iuml;/ï/g
s/&iuml/ï/g
s/&Jcirc;/Ĵ/g
s/&jcirc;/ĵ/g
s/&Jcy;/Й/g
s/&jcy;/й/g
s/&jmath;/ȷ/g
s/&Jsercy;/Ј/g
s/&jsercy;/ј/g
s/&Jukcy;/Є/g
s/&jukcy;/є/g
s/&Kappa;/Κ/g
s/&kappa;/κ/g
s/&kappav;/ϰ/g
s/&Kcedil;/Ķ/g
s/&kcedil;/ķ/g
s/&Kcy;/К/g
s/&kcy;/к/g
s/&kgreen;/ĸ/g
s/&KHcy;/Х/g
s/&khcy;/х/g
s/&KJcy;/Ќ/g
s/&kjcy;/ќ/g
s/&lAarr;/⇚/g
s/&Lacute;/Ĺ/g
s/&lacute;/ĺ/g
s/&laemptyv;/⦴/g
s/&lagran;/ℒ/g
s/&Lambda;/Λ/g
s/&lambda;/λ/g
s/&Lang;/⟪/g
s/&lang;/⟨/g
s/&langd;/⦑/g
s/&langle;/⟨/g
s/&lap;/⪅/g
s/&Laplacetrf;/ℒ/g
s/&laquo;/«/g
s/&laquo/«/g
s/&Larr;/↞/g
s/&lArr;/⇐/g
s/&larr;/←/g
s/&larrb;/⇤/g
s/&larrbfs;/⤟/g
s/&larrfs;/⤝/g
s/&larrhk;/↩/g
s/&larrlp;/↫/g
s/&larrpl;/⤹/g
s/&larrsim;/⥳/g
s/&larrtl;/↢/g
s/&lat;/⪫/g
s/&lAtail;/⤛/g
s/&latail;/⤙/g
s/&late;/⪭/g
s/&lates;/⪭︀/g
s/&lBarr;/⤎/g
s/&lbarr;/⤌/g
s/&lbbrk;/❲/g
s/&lbrace;/{/g
s/&lbrack;/[/g
s/&lbrke;/⦋/g
s/&lbrksld;/⦏/g
s/&lbrkslu;/⦍/g
s/&Lcaron;/Ľ/g
s/&lcaron;/ľ/g
s/&Lcedil;/Ļ/g
s/&lcedil;/ļ/g
s/&lceil;/⌈/g
s/&lcub;/{/g
s/&Lcy;/Л/g
s/&lcy;/л/g
s/&ldca;/⤶/g
s/&ldquo;/“/g
s/&ldquor;/„/g
s/&ldrdhar;/⥧/g
s/&ldrushar;/⥋/g
s/&ldsh;/↲/g
s/&lE;/≦/g
s/&le;/≤/g
s/&LeftAngleBracket;/⟨/g
s/&LeftArrow;/←/g
s/&Leftarrow;/⇐/g
s/&leftarrow;/←/g
s/&LeftArrowBar;/⇤/g
s/&LeftArrowRightArrow;/⇆/g
s/&leftarrowtail;/↢/g
s/&LeftCeiling;/⌈/g
s/&LeftDoubleBracket;/⟦/g
s/&LeftDownTeeVector;/⥡/g
s/&LeftDownVector;/⇃/g
s/&LeftDownVectorBar;/⥙/g
s/&LeftFloor;/⌊/g
s/&leftharpoondown;/↽/g
s/&leftharpoonup;/↼/g
s/&leftleftarrows;/⇇/g
s/&LeftRightArrow;/↔/g
s/&Leftrightarrow;/⇔/g
s/&leftrightarrow;/↔/g
s/&leftrightarrows;/⇆/g
s/&leftrightharpoons;/⇋/g
s/&leftrightsquigarrow;/↭/g
s/&LeftRightVector;/⥎/g
s/&LeftTee;/⊣/g
s/&LeftTeeArrow;/↤/g
s/&LeftTeeVector;/⥚/g
s/&leftthreetimes;/⋋/g
s/&LeftTriangle;/⊲/g
s/&LeftTriangleBar;/⧏/g
s/&LeftTriangleEqual;/⊴/g
s/&LeftUpDownVector;/⥑/g
s/&LeftUpTeeVector;/⥠/g
s/&LeftUpVector;/↿/g
s/&LeftUpVectorBar;/⥘/g
s/&LeftVector;/↼/g
s/&LeftVectorBar;/⥒/g
s/&lEg;/⪋/g
s/&leg;/⋚/g
s/&leq;/≤/g
s/&leqq;/≦/g
s/&leqslant;/⩽/g
s/&les;/⩽/g
s/&lescc;/⪨/g
s/&lesdot;/⩿/g
s/&lesdoto;/⪁/g
s/&lesdotor;/⪃/g
s/&lesg;/⋚︀/g
s/&lesges;/⪓/g
s/&lessapprox;/⪅/g
s/&lessdot;/⋖/g
s/&lesseqgtr;/⋚/g
s/&lesseqqgtr;/⪋/g
s/&LessEqualGreater;/⋚/g
s/&LessFullEqual;/≦/g
s/&LessGreater;/≶/g
s/&lessgtr;/≶/g
s/&LessLess;/⪡/g
s/&lesssim;/≲/g
s/&LessSlantEqual;/⩽/g
s/&LessTilde;/≲/g
s/&lfisht;/⥼/g
s/&lfloor;/⌊/g
s/&lg;/≶/g
s/&lgE;/⪑/g
s/&lHar;/⥢/g
s/&lhard;/↽/g
s/&lharu;/↼/g
s/&lharul;/⥪/g
s/&lhblk;/▄/g
s/&LJcy;/Љ/g
s/&ljcy;/љ/g
s/&Ll;/⋘/g
s/&ll;/≪/g
s/&llarr;/⇇/g
s/&llcorner;/⌞/g
s/&Lleftarrow;/⇚/g
s/&llhard;/⥫/g
s/&lltri;/◺/g
s/&Lmidot;/Ŀ/g
s/&lmidot;/ŀ/g
s/&lmoust;/⎰/g
s/&lmoustache;/⎰/g
s/&lnap;/⪉/g
s/&lnapprox;/⪉/g
s/&lnE;/≨/g
s/&lne;/⪇/g
s/&lneq;/⪇/g
s/&lneqq;/≨/g
s/&lnsim;/⋦/g
s/&loang;/⟬/g
s/&loarr;/⇽/g
s/&lobrk;/⟦/g
s/&LongLeftArrow;/⟵/g
s/&Longleftarrow;/⟸/g
s/&longleftarrow;/⟵/g
s/&LongLeftRightArrow;/⟷/g
s/&Longleftrightarrow;/⟺/g
s/&longleftrightarrow;/⟷/g
s/&longmapsto;/⟼/g
s/&LongRightArrow;/⟶/g
s/&Longrightarrow;/⟹/g
s/&longrightarrow;/⟶/g
s/&looparrowleft;/↫/g
s/&looparrowright;/↬/g
s/&lopar;/⦅/g
s/&loplus;/⨭/g
s/&lotimes;/⨴/g
s/&lowast;/∗/g
s/&lowbar;/_/g
s/&LowerLeftArrow;/↙/g
s/&LowerRightArrow;/↘/g
s/&loz;/◊/g
s/&lozenge;/◊/g
s/&lozf;/⧫/g
s/&lpar;/(/g
s/&lparlt;/⦓/g
s/&lrarr;/⇆/g
s/&lrcorner;/⌟/g
s/&lrhar;/⇋/g
s/&lrhard;/⥭/g
s/&lrm;/‎/g
s/&lrtri;/⊿/g
s/&lsaquo;/‹/g
s/&Lscr;/ℒ/g
s/&Lsh;/↰/g
s/&lsh;/↰/g
s/&lsim;/≲/g
s/&lsime;/⪍/g
s/&lsimg;/⪏/g
s/&lsqb;/[/g
s/&lsquo;/‘/g
s/&lsquor;/‚/g
s/&Lstrok;/Ł/g
s/&lstrok;/ł/g
s/&LT;/</g
s/&LT/</g
s/&Lt;/≪/g
s/&lt;/</g
s/&lt/</g
s/&ltcc;/⪦/g
s/&ltcir;/⩹/g
s/&ltdot;/⋖/g
s/&lthree;/⋋/g
s/&ltimes;/⋉/g
s/&ltlarr;/⥶/g
s/&ltquest;/⩻/g
s/&ltri;/◃/g
s/&ltrie;/⊴/g
s/&ltrif;/◂/g
s/&ltrPar;/⦖/g
s/&lurdshar;/⥊/g
s/&luruhar;/⥦/g
s/&lvertneqq;/≨︀/g
s/&lvnE;/≨︀/g
s/&macr;/¯/g
s/&macr/¯/g
s/&male;/♂/g
s/&malt;/✠/g
s/&maltese;/✠/g
s/&Map;/⤅/g
s/&map;/↦/g
s/&mapsto;/↦/g
s/&mapstodown;/↧/g
s/&mapstoleft;/↤/g
s/&mapstoup;/↥/g
s/&marker;/▮/g
s/&mcomma;/⨩/g
s/&Mcy;/М/g
s/&mcy;/м/g
s/&mdash;/—/g
s/&mDDot;/∺/g
s/&measuredangle;/∡/g
s/&MediumSpace;/ /g
s/&Mellintrf;/ℳ/g
s/&mho;/℧/g
s/&micro;/µ/g
s/&micro/µ/g
s/&mid;/∣/g
s/&midast;/*/g
s/&midcir;/⫰/g
s/&middot;/·/g
s/&middot/·/g
s/&minus;/−/g
s/&minusb;/⊟/g
s/&minusd;/∸/g
s/&minusdu;/⨪/g
s/&MinusPlus;/∓/g
s/&mlcp;/⫛/g
s/&mldr;/…/g
s/&mnplus;/∓/g
s/&models;/⊧/g
s/&mp;/∓/g
s/&Mscr;/ℳ/g
s/&mstpos;/∾/g
s/&Mu;/Μ/g
s/&mu;/μ/g
s/&multimap;/⊸/g
s/&mumap;/⊸/g
s/&nabla;/∇/g
s/&Nacute;/Ń/g
s/&nacute;/ń/g
s/&nang;/∠⃒/g
s/&nap;/≉/g
s/&napE;/⩰̸/g
s/&napid;/≋̸/g
s/&napos;/ŉ/g
s/&napprox;/≉/g
s/&natur;/♮/g
s/&natural;/♮/g
s/&naturals;/ℕ/g
s/&nbsp;/ /g
s/&nbsp/ /g
s/&nbump;/≎̸/g
s/&nbumpe;/≏̸/g
s/&ncap;/⩃/g
s/&Ncaron;/Ň/g
s/&ncaron;/ň/g
s/&Ncedil;/Ņ/g
s/&ncedil;/ņ/g
s/&ncong;/≇/g
s/&ncongdot;/⩭̸/g
s/&ncup;/⩂/g
s/&Ncy;/Н/g
s/&ncy;/н/g
s/&ndash;/–/g
s/&ne;/≠/g
s/&nearhk;/⤤/g
s/&neArr;/⇗/g
s/&nearr;/↗/g
s/&nearrow;/↗/g
s/&nedot;/≐̸/g
s/&NegativeMediumSpace;/​/g
s/&NegativeThickSpace;/​/g
s/&NegativeThinSpace;/​/g
s/&NegativeVeryThinSpace;/​/g
s/&nequiv;/≢/g
s/&nesear;/⤨/g
s/&nesim;/≂̸/g
s/&NestedGreaterGreater;/≫/g
s/&NestedLessLess;/≪/g
s/&NewLine;/\n/g
s/&nexist;/∄/g
s/&nexists;/∄/g
s/&ngE;/≧̸/g
s/&nge;/≱/g
s/&ngeq;/≱/g
s/&ngeqq;/≧̸/g
s/&ngeqslant;/⩾̸/g
s/&nges;/⩾̸/g
s/&nGg;/⋙̸/g
s/&ngsim;/≵/g
s/&nGt;/≫⃒/g
s/&ngt;/≯/g
s/&ngtr;/≯/g
s/&nGtv;/≫̸/g
s/&nhArr;/⇎/g
s/&nharr;/↮/g
s/&nhpar;/⫲/g
s/&ni;/∋/g
s/&nis;/⋼/g
s/&nisd;/⋺/g
s/&niv;/∋/g
s/&NJcy;/Њ/g
s/&njcy;/њ/g
s/&nlArr;/⇍/g
s/&nlarr;/↚/g
s/&nldr;/‥/g
s/&nlE;/≦̸/g
s/&nle;/≰/g
s/&nLeftarrow;/⇍/g
s/&nleftarrow;/↚/g
s/&nLeftrightarrow;/⇎/g
s/&nleftrightarrow;/↮/g
s/&nleq;/≰/g
s/&nleqq;/≦̸/g
s/&nleqslant;/⩽̸/g
s/&nles;/⩽̸/g
s/&nless;/≮/g
s/&nLl;/⋘̸/g
s/&nlsim;/≴/g
s/&nLt;/≪⃒/g
s/&nlt;/≮/g
s/&nltri;/⋪/g
s/&nltrie;/⋬/g
s/&nLtv;/≪̸/g
s/&nmid;/∤/g
s/&NoBreak;/⁠/g
s/&NonBreakingSpace;/ /g
s/&Nopf;/ℕ/g
s/&Not;/⫬/g
s/&not;/¬/g
s/&not/¬/g
s/&NotCongruent;/≢/g
s/&NotCupCap;/≭/g
s/&NotDoubleVerticalBar;/∦/g
s/&NotElement;/∉/g
s/&NotEqual;/≠/g
s/&NotEqualTilde;/≂̸/g
s/&NotExists;/∄/g
s/&NotGreater;/≯/g
s/&NotGreaterEqual;/≱/g
s/&NotGreaterFullEqual;/≧̸/g
s/&NotGreaterGreater;/≫̸/g
s/&NotGreaterLess;/≹/g
s/&NotGreaterSlantEqual;/⩾̸/g
s/&NotGreaterTilde;/≵/g
s/&NotHumpDownHump;/≎̸/g
s/&NotHumpEqual;/≏̸/g
s/&notin;/∉/g
s/&notindot;/⋵̸/g
s/&notinE;/⋹̸/g
s/&notinva;/∉/g
s/&notinvb;/⋷/g
s/&notinvc;/⋶/g
s/&NotLeftTriangle;/⋪/g
s/&NotLeftTriangleBar;/⧏̸/g
s/&NotLeftTriangleEqual;/⋬/g
s/&NotLess;/≮/g
s/&NotLessEqual;/≰/g
s/&NotLessGreater;/≸/g
s/&NotLessLess;/≪̸/g
s/&NotLessSlantEqual;/⩽̸/g
s/&NotLessTilde;/≴/g
s/&NotNestedGreaterGreater;/⪢̸/g
s/&NotNestedLessLess;/⪡̸/g
s/&notni;/∌/g
s/&notniva;/∌/g
s/&notnivb;/⋾/g
s/&notnivc;/⋽/g
s/&NotPrecedes;/⊀/g
s/&NotPrecedesEqual;/⪯̸/g
s/&NotPrecedesSlantEqual;/⋠/g
s/&NotReverseElement;/∌/g
s/&NotRightTriangle;/⋫/g
s/&NotRightTriangleBar;/⧐̸/g
s/&NotRightTriangleEqual;/⋭/g
s/&NotSquareSubset;/⊏̸/g
s/&NotSquareSubsetEqual;/⋢/g
s/&NotSquareSuperset;/⊐̸/g
s/&NotSquareSupersetEqual;/⋣/g
s/&NotSubset;/⊂⃒/g
s/&NotSubsetEqual;/⊈/g
s/&NotSucceeds;/⊁/g
s/&NotSucceedsEqual;/⪰̸/g
s/&NotSucceedsSlantEqual;/⋡/g
s/&NotSucceedsTilde;/≿̸/g
s/&NotSuperset;/⊃⃒/g
s/&NotSupersetEqual;/⊉/g
s/&NotTilde;/≁/g
s/&NotTildeEqual;/≄/g
s/&NotTildeFullEqual;/≇/g
s/&NotTildeTilde;/≉/g
s/&NotVerticalBar;/∤/g
s/&npar;/∦/g
s/&nparallel;/∦/g
s/&nparsl;/⫽⃥/g
s/&npart;/∂̸/g
s/&npolint;/⨔/g
s/&npr;/⊀/g
s/&nprcue;/⋠/g
s/&npre;/⪯̸/g
s/&nprec;/⊀/g
s/&npreceq;/⪯̸/g
s/&nrArr;/⇏/g
s/&nrarr;/↛/g
s/&nrarrc;/⤳̸/g
s/&nrarrw;/↝̸/g
s/&nRightarrow;/⇏/g
s/&nrightarrow;/↛/g
s/&nrtri;/⋫/g
s/&nrtrie;/⋭/g
s/&nsc;/⊁/g
s/&nsccue;/⋡/g
s/&nsce;/⪰̸/g
s/&nshortmid;/∤/g
s/&nshortparallel;/∦/g
s/&nsim;/≁/g
s/&nsime;/≄/g
s/&nsimeq;/≄/g
s/&nsmid;/∤/g
s/&nspar;/∦/g
s/&nsqsube;/⋢/g
s/&nsqsupe;/⋣/g
s/&nsub;/⊄/g
s/&nsubE;/⫅̸/g
s/&nsube;/⊈/g
s/&nsubset;/⊂⃒/g
s/&nsubseteq;/⊈/g
s/&nsubseteqq;/⫅̸/g
s/&nsucc;/⊁/g
s/&nsucceq;/⪰̸/g
s/&nsup;/⊅/g
s/&nsupE;/⫆̸/g
s/&nsupe;/⊉/g
s/&nsupset;/⊃⃒/g
s/&nsupseteq;/⊉/g
s/&nsupseteqq;/⫆̸/g
s/&ntgl;/≹/g
s/&Ntilde;/Ñ/g
s/&Ntilde/Ñ/g
s/&ntilde;/ñ/g
s/&ntilde/ñ/g
s/&ntlg;/≸/g
s/&ntriangleleft;/⋪/g
s/&ntrianglelefteq;/⋬/g
s/&ntriangleright;/⋫/g
s/&ntrianglerighteq;/⋭/g
s/&Nu;/Ν/g
s/&nu;/ν/g
s/&num;/#/g
s/&numero;/№/g
s/&numsp;/ /g
s/&nvap;/≍⃒/g
s/&nVDash;/⊯/g
s/&nVdash;/⊮/g
s/&nvDash;/⊭/g
s/&nvdash;/⊬/g
s/&nvge;/≥⃒/g
s/&nvgt;/>⃒/g
s/&nvHarr;/⤄/g
s/&nvinfin;/⧞/g
s/&nvlArr;/⤂/g
s/&nvle;/≤⃒/g
s/&nvlt;/<⃒/g
s/&nvltrie;/⊴⃒/g
s/&nvrArr;/⤃/g
s/&nvrtrie;/⊵⃒/g
s/&nvsim;/∼⃒/g
s/&nwarhk;/⤣/g
s/&nwArr;/⇖/g
s/&nwarr;/↖/g
s/&nwarrow;/↖/g
s/&nwnear;/⤧/g
s/&Oacute;/Ó/g
s/&Oacute/Ó/g
s/&oacute;/ó/g
s/&oacute/ó/g
s/&oast;/⊛/g
s/&ocir;/⊚/g
s/&Ocirc;/Ô/g
s/&Ocirc/Ô/g
s/&ocirc;/ô/g
s/&ocirc/ô/g
s/&Ocy;/О/g
s/&ocy;/о/g
s/&odash;/⊝/g
s/&Odblac;/Ő/g
s/&odblac;/ő/g
s/&odiv;/⨸/g
s/&odot;/⊙/g
s/&odsold;/⦼/g
s/&OElig;/Œ/g
s/&oelig;/œ/g
s/&ofcir;/⦿/g
s/&ogon;/˛/g
s/&Ograve;/Ò/g
s/&Ograve/Ò/g
s/&ograve;/ò/g
s/&ograve/ò/g
s/&ogt;/⧁/g
s/&ohbar;/⦵/g
s/&ohm;/Ω/g
s/&oint;/∮/g
s/&olarr;/↺/g
s/&olcir;/⦾/g
s/&olcross;/⦻/g
s/&oline;/‾/g
s/&olt;/⧀/g
s/&Omacr;/Ō/g
s/&omacr;/ō/g
s/&Omega;/Ω/g
s/&omega;/ω/g
s/&Omicron;/Ο/g
s/&omicron;/ο/g
s/&omid;/⦶/g
s/&ominus;/⊖/g
s/&opar;/⦷/g
s/&OpenCurlyDoubleQuote;/“/g
s/&OpenCurlyQuote;/‘/g
s/&operp;/⦹/g
s/&oplus;/⊕/g
s/&Or;/⩔/g
s/&or;/∨/g
s/&orarr;/↻/g
s/&ord;/⩝/g
s/&order;/ℴ/g
s/&orderof;/ℴ/g
s/&ordf;/ª/g
s/&ordf/ª/g
s/&ordm;/º/g
s/&ordm/º/g
s/&origof;/⊶/g
s/&oror;/⩖/g
s/&orslope;/⩗/g
s/&orv;/⩛/g
s/&oS;/Ⓢ/g
s/&oscr;/ℴ/g
s/&Oslash;/Ø/g
s/&Oslash/Ø/g
s/&oslash;/ø/g
s/&oslash/ø/g
s/&osol;/⊘/g
s/&Otilde;/Õ/g
s/&Otilde/Õ/g
s/&otilde;/õ/g
s/&otilde/õ/g
s/&Otimes;/⨷/g
s/&otimes;/⊗/g
s/&otimesas;/⨶/g
s/&Ouml;/Ö/g
s/&Ouml/Ö/g
s/&ouml;/ö/g
s/&ouml/ö/g
s/&ovbar;/⌽/g
s/&OverBar;/‾/g
s/&OverBrace;/⏞/g
s/&OverBracket;/⎴/g
s/&OverParenthesis;/⏜/g
s/&par;/∥/g
s/&para;/¶/g
s/&para/¶/g
s/&parallel;/∥/g
s/&parsim;/⫳/g
s/&parsl;/⫽/g
s/&part;/∂/g
s/&PartialD;/∂/g
s/&Pcy;/П/g
s/&pcy;/п/g
s/&percnt;/%/g
s/&period;/./g
s/&permil;/‰/g
s/&perp;/⊥/g
s/&pertenk;/‱/g
s/&Phi;/Φ/g
s/&phi;/φ/g
s/&phiv;/ϕ/g
s/&phmmat;/ℳ/g
s/&phone;/☎/g
s/&Pi;/Π/g
s/&pi;/π/g
s/&pitchfork;/⋔/g
s/&piv;/ϖ/g
s/&planck;/ℏ/g
s/&planckh;/ℎ/g
s/&plankv;/ℏ/g
s/&plus;/+/g
s/&plusacir;/⨣/g
s/&plusb;/⊞/g
s/&pluscir;/⨢/g
s/&plusdo;/∔/g
s/&plusdu;/⨥/g
s/&pluse;/⩲/g
s/&PlusMinus;/±/g
s/&plusmn;/±/g
s/&plusmn/±/g
s/&plussim;/⨦/g
s/&plustwo;/⨧/g
s/&pm;/±/g
s/&Poincareplane;/ℌ/g
s/&pointint;/⨕/g
s/&Popf;/ℙ/g
s/&pound;/£/g
s/&pound/£/g
s/&Pr;/⪻/g
s/&pr;/≺/g
s/&prap;/⪷/g
s/&prcue;/≼/g
s/&prE;/⪳/g
s/&pre;/⪯/g
s/&prec;/≺/g
s/&precapprox;/⪷/g
s/&preccurlyeq;/≼/g
s/&Precedes;/≺/g
s/&PrecedesEqual;/⪯/g
s/&PrecedesSlantEqual;/≼/g
s/&PrecedesTilde;/≾/g
s/&preceq;/⪯/g
s/&precnapprox;/⪹/g
s/&precneqq;/⪵/g
s/&precnsim;/⋨/g
s/&precsim;/≾/g
s/&Prime;/″/g
s/&prime;/′/g
s/&primes;/ℙ/g
s/&prnap;/⪹/g
s/&prnE;/⪵/g
s/&prnsim;/⋨/g
s/&prod;/∏/g
s/&Product;/∏/g
s/&profalar;/⌮/g
s/&profline;/⌒/g
s/&profsurf;/⌓/g
s/&prop;/∝/g
s/&Proportion;/∷/g
s/&Proportional;/∝/g
s/&propto;/∝/g
s/&prsim;/≾/g
s/&prurel;/⊰/g
s/&Psi;/Ψ/g
s/&psi;/ψ/g
s/&puncsp;/ /g
s/&qint;/⨌/g
s/&Qopf;/ℚ/g
s/&qprime;/⁗/g
s/&quaternions;/ℍ/g
s/&quatint;/⨖/g
s/&quest;/?/g
s/&questeq;/≟/g
s/&QUOT;/"/g
s/&QUOT/"/g
s/&quot;/"/g
s/&quot/"/g
s/&rAarr;/⇛/g
s/&race;/∽̱/g
s/&Racute;/Ŕ/g
s/&racute;/ŕ/g
s/&radic;/√/g
s/&raemptyv;/⦳/g
s/&Rang;/⟫/g
s/&rang;/⟩/g
s/&rangd;/⦒/g
s/&range;/⦥/g
s/&rangle;/⟩/g
s/&raquo;/»/g
s/&raquo/»/g
s/&Rarr;/↠/g
s/&rArr;/⇒/g
s/&rarr;/→/g
s/&rarrap;/⥵/g
s/&rarrb;/⇥/g
s/&rarrbfs;/⤠/g
s/&rarrc;/⤳/g
s/&rarrfs;/⤞/g
s/&rarrhk;/↪/g
s/&rarrlp;/↬/g
s/&rarrpl;/⥅/g
s/&rarrsim;/⥴/g
s/&Rarrtl;/⤖/g
s/&rarrtl;/↣/g
s/&rarrw;/↝/g
s/&rAtail;/⤜/g
s/&ratail;/⤚/g
s/&ratio;/∶/g
s/&rationals;/ℚ/g
s/&RBarr;/⤐/g
s/&rBarr;/⤏/g
s/&rbarr;/⤍/g
s/&rbbrk;/❳/g
s/&rbrace;/}/g
s/&rbrack;/]/g
s/&rbrke;/⦌/g
s/&rbrksld;/⦎/g
s/&rbrkslu;/⦐/g
s/&Rcaron;/Ř/g
s/&rcaron;/ř/g
s/&Rcedil;/Ŗ/g
s/&rcedil;/ŗ/g
s/&rceil;/⌉/g
s/&rcub;/}/g
s/&Rcy;/Р/g
s/&rcy;/р/g
s/&rdca;/⤷/g
s/&rdldhar;/⥩/g
s/&rdquo;/”/g
s/&rdquor;/”/g
s/&rdsh;/↳/g
s/&Re;/ℜ/g
s/&real;/ℜ/g
s/&realine;/ℛ/g
s/&realpart;/ℜ/g
s/&reals;/ℝ/g
s/&rect;/▭/g
s/&REG;/®/g
s/&REG/®/g
s/&reg;/®/g
s/&reg/®/g
s/&ReverseElement;/∋/g
s/&ReverseEquilibrium;/⇋/g
s/&ReverseUpEquilibrium;/⥯/g
s/&rfisht;/⥽/g
s/&rfloor;/⌋/g
s/&Rfr;/ℜ/g
s/&rHar;/⥤/g
s/&rhard;/⇁/g
s/&rharu;/⇀/g
s/&rharul;/⥬/g
s/&Rho;/Ρ/g
s/&rho;/ρ/g
s/&rhov;/ϱ/g
s/&RightAngleBracket;/⟩/g
s/&RightArrow;/→/g
s/&Rightarrow;/⇒/g
s/&rightarrow;/→/g
s/&RightArrowBar;/⇥/g
s/&RightArrowLeftArrow;/⇄/g
s/&rightarrowtail;/↣/g
s/&RightCeiling;/⌉/g
s/&RightDoubleBracket;/⟧/g
s/&RightDownTeeVector;/⥝/g
s/&RightDownVector;/⇂/g
s/&RightDownVectorBar;/⥕/g
s/&RightFloor;/⌋/g
s/&rightharpoondown;/⇁/g
s/&rightharpoonup;/⇀/g
s/&rightleftarrows;/⇄/g
s/&rightleftharpoons;/⇌/g
s/&rightrightarrows;/⇉/g
s/&rightsquigarrow;/↝/g
s/&RightTee;/⊢/g
s/&RightTeeArrow;/↦/g
s/&RightTeeVector;/⥛/g
s/&rightthreetimes;/⋌/g
s/&RightTriangle;/⊳/g
s/&RightTriangleBar;/⧐/g
s/&RightTriangleEqual;/⊵/g
s/&RightUpDownVector;/⥏/g
s/&RightUpTeeVector;/⥜/g
s/&RightUpVector;/↾/g
s/&RightUpVectorBar;/⥔/g
s/&RightVector;/⇀/g
s/&RightVectorBar;/⥓/g
s/&ring;/˚/g
s/&risingdotseq;/≓/g
s/&rlarr;/⇄/g
s/&rlhar;/⇌/g
s/&rlm;/‏/g
s/&rmoust;/⎱/g
s/&rmoustache;/⎱/g
s/&rnmid;/⫮/g
s/&roang;/⟭/g
s/&roarr;/⇾/g
s/&robrk;/⟧/g
s/&ropar;/⦆/g
s/&Ropf;/ℝ/g
s/&roplus;/⨮/g
s/&rotimes;/⨵/g
s/&RoundImplies;/⥰/g
s/&rpar;/)/g
s/&rpargt;/⦔/g
s/&rppolint;/⨒/g
s/&rrarr;/⇉/g
s/&Rrightarrow;/⇛/g
s/&rsaquo;/›/g
s/&Rscr;/ℛ/g
s/&Rsh;/↱/g
s/&rsh;/↱/g
s/&rsqb;/]/g
s/&rsquo;/’/g
s/&rsquor;/’/g
s/&rthree;/⋌/g
s/&rtimes;/⋊/g
s/&rtri;/▹/g
s/&rtrie;/⊵/g
s/&rtrif;/▸/g
s/&rtriltri;/⧎/g
s/&RuleDelayed;/⧴/g
s/&ruluhar;/⥨/g
s/&rx;/℞/g
s/&Sacute;/Ś/g
s/&sacute;/ś/g
s/&sbquo;/‚/g
s/&Sc;/⪼/g
s/&sc;/≻/g
s/&scap;/⪸/g
s/&Scaron;/Š/g
s/&scaron;/š/g
s/&sccue;/≽/g
s/&scE;/⪴/g
s/&sce;/⪰/g
s/&Scedil;/Ş/g
s/&scedil;/ş/g
s/&Scirc;/Ŝ/g
s/&scirc;/ŝ/g
s/&scnap;/⪺/g
s/&scnE;/⪶/g
s/&scnsim;/⋩/g
s/&scpolint;/⨓/g
s/&scsim;/≿/g
s/&Scy;/С/g
s/&scy;/с/g
s/&sdot;/⋅/g
s/&sdotb;/⊡/g
s/&sdote;/⩦/g
s/&searhk;/⤥/g
s/&seArr;/⇘/g
s/&searr;/↘/g
s/&searrow;/↘/g
s/&sect;/§/g
s/&sect/§/g
s/&semi;/;/g
s/&seswar;/⤩/g
s/&setminus;/∖/g
s/&setmn;/∖/g
s/&sext;/✶/g
s/&sfrown;/⌢/g
s/&sharp;/♯/g
s/&SHCHcy;/Щ/g
s/&shchcy;/щ/g
s/&SHcy;/Ш/g
s/&shcy;/ш/g
s/&ShortDownArrow;/↓/g
s/&ShortLeftArrow;/←/g
s/&shortmid;/∣/g
s/&shortparallel;/∥/g
s/&ShortRightArrow;/→/g
s/&ShortUpArrow;/↑/g
s/&shy;/­/g
s/&shy/­/g
s/&Sigma;/Σ/g
s/&sigma;/σ/g
s/&sigmaf;/ς/g
s/&sigmav;/ς/g
s/&sim;/∼/g
s/&simdot;/⩪/g
s/&sime;/≃/g
s/&simeq;/≃/g
s/&simg;/⪞/g
s/&simgE;/⪠/g
s/&siml;/⪝/g
s/&simlE;/⪟/g
s/&simne;/≆/g
s/&simplus;/⨤/g
s/&simrarr;/⥲/g
s/&slarr;/←/g
s/&SmallCircle;/∘/g
s/&smallsetminus;/∖/g
s/&smashp;/⨳/g
s/&smeparsl;/⧤/g
s/&smid;/∣/g
s/&smile;/⌣/g
s/&smt;/⪪/g
s/&smte;/⪬/g
s/&smtes;/⪬︀/g
s/&SOFTcy;/Ь/g
s/&softcy;/ь/g
s/&sol;/\//g
s/&solb;/⧄/g
s/&solbar;/⌿/g
s/&spades;/♠/g
s/&spadesuit;/♠/g
s/&spar;/∥/g
s/&sqcap;/⊓/g
s/&sqcaps;/⊓︀/g
s/&sqcup;/⊔/g
s/&sqcups;/⊔︀/g
s/&Sqrt;/√/g
s/&sqsub;/⊏/g
s/&sqsube;/⊑/g
s/&sqsubset;/⊏/g
s/&sqsubseteq;/⊑/g
s/&sqsup;/⊐/g
s/&sqsupe;/⊒/g
s/&sqsupset;/⊐/g
s/&sqsupseteq;/⊒/g
s/&squ;/□/g
s/&Square;/□/g
s/&square;/□/g
s/&SquareIntersection;/⊓/g
s/&SquareSubset;/⊏/g
s/&SquareSubsetEqual;/⊑/g
s/&SquareSuperset;/⊐/g
s/&SquareSupersetEqual;/⊒/g
s/&SquareUnion;/⊔/g
s/&squarf;/▪/g
s/&squf;/▪/g
s/&srarr;/→/g
s/&ssetmn;/∖/g
s/&ssmile;/⌣/g
s/&sstarf;/⋆/g
s/&Star;/⋆/g
s/&star;/☆/g
s/&starf;/★/g
s/&straightepsilon;/ϵ/g
s/&straightphi;/ϕ/g
s/&strns;/¯/g
s/&Sub;/⋐/g
s/&sub;/⊂/g
s/&subdot;/⪽/g
s/&subE;/⫅/g
s/&sube;/⊆/g
s/&subedot;/⫃/g
s/&submult;/⫁/g
s/&subnE;/⫋/g
s/&subne;/⊊/g
s/&subplus;/⪿/g
s/&subrarr;/⥹/g
s/&Subset;/⋐/g
s/&subset;/⊂/g
s/&subseteq;/⊆/g
s/&subseteqq;/⫅/g
s/&SubsetEqual;/⊆/g
s/&subsetneq;/⊊/g
s/&subsetneqq;/⫋/g
s/&subsim;/⫇/g
s/&subsub;/⫕/g
s/&subsup;/⫓/g
s/&succ;/≻/g
s/&succapprox;/⪸/g
s/&succcurlyeq;/≽/g
s/&Succeeds;/≻/g
s/&SucceedsEqual;/⪰/g
s/&SucceedsSlantEqual;/≽/g
s/&SucceedsTilde;/≿/g
s/&succeq;/⪰/g
s/&succnapprox;/⪺/g
s/&succneqq;/⪶/g
s/&succnsim;/⋩/g
s/&succsim;/≿/g
s/&SuchThat;/∋/g
s/&Sum;/∑/g
s/&sum;/∑/g
s/&sung;/♪/g
s/&Sup;/⋑/g
s/&sup;/⊃/g
s/&sup1;/¹/g
s/&sup1/¹/g
s/&sup2;/²/g
s/&sup2/²/g
s/&sup3;/³/g
s/&sup3/³/g
s/&supdot;/⪾/g
s/&supdsub;/⫘/g
s/&supE;/⫆/g
s/&supe;/⊇/g
s/&supedot;/⫄/g
s/&Superset;/⊃/g
s/&SupersetEqual;/⊇/g
s/&suphsol;/⟉/g
s/&suphsub;/⫗/g
s/&suplarr;/⥻/g
s/&supmult;/⫂/g
s/&supnE;/⫌/g
s/&supne;/⊋/g
s/&supplus;/⫀/g
s/&Supset;/⋑/g
s/&supset;/⊃/g
s/&supseteq;/⊇/g
s/&supseteqq;/⫆/g
s/&supsetneq;/⊋/g
s/&supsetneqq;/⫌/g
s/&supsim;/⫈/g
s/&supsub;/⫔/g
s/&supsup;/⫖/g
s/&swarhk;/⤦/g
s/&swArr;/⇙/g
s/&swarr;/↙/g
s/&swarrow;/↙/g
s/&swnwar;/⤪/g
s/&szlig;/ß/g
s/&szlig/ß/g
s/&Tab;/	/g
s/&target;/⌖/g
s/&Tau;/Τ/g
s/&tau;/τ/g
s/&tbrk;/⎴/g
s/&Tcaron;/Ť/g
s/&tcaron;/ť/g
s/&Tcedil;/Ţ/g
s/&tcedil;/ţ/g
s/&Tcy;/Т/g
s/&tcy;/т/g
s/&tdot;/⃛/g
s/&telrec;/⌕/g
s/&there4;/∴/g
s/&Therefore;/∴/g
s/&therefore;/∴/g
s/&Theta;/Θ/g
s/&theta;/θ/g
s/&thetasym;/ϑ/g
s/&thetav;/ϑ/g
s/&thickapprox;/≈/g
s/&thicksim;/∼/g
s/&ThickSpace;/  /g
s/&thinsp;/ /g
s/&ThinSpace;/ /g
s/&thkap;/≈/g
s/&thksim;/∼/g
s/&THORN;/Þ/g
s/&THORN/Þ/g
s/&thorn;/þ/g
s/&thorn/þ/g
s/&Tilde;/∼/g
s/&tilde;/˜/g
s/&TildeEqual;/≃/g
s/&TildeFullEqual;/≅/g
s/&TildeTilde;/≈/g
s/&times;/×/g
s/&times/×/g
s/&timesb;/⊠/g
s/&timesbar;/⨱/g
s/&timesd;/⨰/g
s/&tint;/∭/g
s/&toea;/⤨/g
s/&top;/⊤/g
s/&topbot;/⌶/g
s/&topcir;/⫱/g
s/&topfork;/⫚/g
s/&tosa;/⤩/g
s/&tprime;/‴/g
s/&TRADE;/™/g
s/&trade;/™/g
s/&triangle;/▵/g
s/&triangledown;/▿/g
s/&triangleleft;/◃/g
s/&trianglelefteq;/⊴/g
s/&triangleq;/≜/g
s/&triangleright;/▹/g
s/&trianglerighteq;/⊵/g
s/&tridot;/◬/g
s/&trie;/≜/g
s/&triminus;/⨺/g
s/&TripleDot;/⃛/g
s/&triplus;/⨹/g
s/&trisb;/⧍/g
s/&tritime;/⨻/g
s/&trpezium;/⏢/g
s/&TScy;/Ц/g
s/&tscy;/ц/g
s/&TSHcy;/Ћ/g
s/&tshcy;/ћ/g
s/&Tstrok;/Ŧ/g
s/&tstrok;/ŧ/g
s/&twixt;/≬/g
s/&twoheadleftarrow;/↞/g
s/&twoheadrightarrow;/↠/g
s/&Uacute;/Ú/g
s/&Uacute/Ú/g
s/&uacute;/ú/g
s/&uacute/ú/g
s/&Uarr;/↟/g
s/&uArr;/⇑/g
s/&uarr;/↑/g
s/&Uarrocir;/⥉/g
s/&Ubrcy;/Ў/g
s/&ubrcy;/ў/g
s/&Ubreve;/Ŭ/g
s/&ubreve;/ŭ/g
s/&Ucirc;/Û/g
s/&Ucirc/Û/g
s/&ucirc;/û/g
s/&ucirc/û/g
s/&Ucy;/У/g
s/&ucy;/у/g
s/&udarr;/⇅/g
s/&Udblac;/Ű/g
s/&udblac;/ű/g
s/&udhar;/⥮/g
s/&ufisht;/⥾/g
s/&Ugrave;/Ù/g
s/&Ugrave/Ù/g
s/&ugrave;/ù/g
s/&ugrave/ù/g
s/&uHar;/⥣/g
s/&uharl;/↿/g
s/&uharr;/↾/g
s/&uhblk;/▀/g
s/&ulcorn;/⌜/g
s/&ulcorner;/⌜/g
s/&ulcrop;/⌏/g
s/&ultri;/◸/g
s/&Umacr;/Ū/g
s/&umacr;/ū/g
s/&uml;/¨/g
s/&uml/¨/g
s/&UnderBar;/_/g
s/&UnderBrace;/⏟/g
s/&UnderBracket;/⎵/g
s/&UnderParenthesis;/⏝/g
s/&Union;/⋃/g
s/&UnionPlus;/⊎/g
s/&Uogon;/Ų/g
s/&uogon;/ų/g
s/&UpArrow;/↑/g
s/&Uparrow;/⇑/g
s/&uparrow;/↑/g
s/&UpArrowBar;/⤒/g
s/&UpArrowDownArrow;/⇅/g
s/&UpDownArrow;/↕/g
s/&Updownarrow;/⇕/g
s/&updownarrow;/↕/g
s/&UpEquilibrium;/⥮/g
s/&upharpoonleft;/↿/g
s/&upharpoonright;/↾/g
s/&uplus;/⊎/g
s/&UpperLeftArrow;/↖/g
s/&UpperRightArrow;/↗/g
s/&Upsi;/ϒ/g
s/&upsi;/υ/g
s/&upsih;/ϒ/g
s/&Upsilon;/Υ/g
s/&upsilon;/υ/g
s/&UpTee;/⊥/g
s/&UpTeeArrow;/↥/g
s/&upuparrows;/⇈/g
s/&urcorn;/⌝/g
s/&urcorner;/⌝/g
s/&urcrop;/⌎/g
s/&Uring;/Ů/g
s/&uring;/ů/g
s/&urtri;/◹/g
s/&utdot;/⋰/g
s/&Utilde;/Ũ/g
s/&utilde;/ũ/g
s/&utri;/▵/g
s/&utrif;/▴/g
s/&uuarr;/⇈/g
s/&Uuml;/Ü/g
s/&Uuml/Ü/g
s/&uuml;/ü/g
s/&uuml/ü/g
s/&uwangle;/⦧/g
s/&vangrt;/⦜/g
s/&varepsilon;/ϵ/g
s/&varkappa;/ϰ/g
s/&varnothing;/∅/g
s/&varphi;/ϕ/g
s/&varpi;/ϖ/g
s/&varpropto;/∝/g
s/&vArr;/⇕/g
s/&varr;/↕/g
s/&varrho;/ϱ/g
s/&varsigma;/ς/g
s/&varsubsetneq;/⊊︀/g
s/&varsubsetneqq;/⫋︀/g
s/&varsupsetneq;/⊋︀/g
s/&varsupsetneqq;/⫌︀/g
s/&vartheta;/ϑ/g
s/&vartriangleleft;/⊲/g
s/&vartriangleright;/⊳/g
s/&Vbar;/⫫/g
s/&vBar;/⫨/g
s/&vBarv;/⫩/g
s/&Vcy;/В/g
s/&vcy;/в/g
s/&VDash;/⊫/g
s/&Vdash;/⊩/g
s/&vDash;/⊨/g
s/&vdash;/⊢/g
s/&Vdashl;/⫦/g
s/&Vee;/⋁/g
s/&vee;/∨/g
s/&veebar;/⊻/g
s/&veeeq;/≚/g
s/&vellip;/⋮/g
s/&Verbar;/‖/g
s/&verbar;/|/g
s/&Vert;/‖/g
s/&vert;/|/g
s/&VerticalBar;/∣/g
s/&VerticalLine;/|/g
s/&VerticalSeparator;/❘/g
s/&VerticalTilde;/≀/g
s/&VeryThinSpace;/ /g
s/&vltri;/⊲/g
s/&vnsub;/⊂⃒/g
s/&vnsup;/⊃⃒/g
s/&vprop;/∝/g
s/&vrtri;/⊳/g
s/&vsubnE;/⫋︀/g
s/&vsubne;/⊊︀/g
s/&vsupnE;/⫌︀/g
s/&vsupne;/⊋︀/g
s/&Vvdash;/⊪/g
s/&vzigzag;/⦚/g
s/&Wcirc;/Ŵ/g
s/&wcirc;/ŵ/g
s/&wedbar;/⩟/g
s/&Wedge;/⋀/g
s/&wedge;/∧/g
s/&wedgeq;/≙/g
s/&weierp;/℘/g
s/&wp;/℘/g
s/&wr;/≀/g
s/&wreath;/≀/g
s/&xcap;/⋂/g
s/&xcirc;/◯/g
s/&xcup;/⋃/g
s/&xdtri;/▽/g
s/&xhArr;/⟺/g
s/&xharr;/⟷/g
s/&Xi;/Ξ/g
s/&xi;/ξ/g
s/&xlArr;/⟸/g
s/&xlarr;/⟵/g
s/&xmap;/⟼/g
s/&xnis;/⋻/g
s/&xodot;/⨀/g
s/&xoplus;/⨁/g
s/&xotime;/⨂/g
s/&xrArr;/⟹/g
s/&xrarr;/⟶/g
s/&xsqcup;/⨆/g
s/&xuplus;/⨄/g
s/&xutri;/△/g
s/&xvee;/⋁/g
s/&xwedge;/⋀/g
s/&Yacute;/Ý/g
s/&Yacute/Ý/g
s/&yacute;/ý/g
s/&yacute/ý/g
s/&YAcy;/Я/g
s/&yacy;/я/g
s/&Ycirc;/Ŷ/g
s/&ycirc;/ŷ/g
s/&Ycy;/Ы/g
s/&ycy;/ы/g
s/&yen;/¥/g
s/&yen/¥/g
s/&YIcy;/Ї/g
s/&yicy;/ї/g
s/&YUcy;/Ю/g
s/&yucy;/ю/g
s/&Yuml;/Ÿ/g
s/&yuml;/ÿ/g
s/&yuml/ÿ/g
s/&Zacute;/Ź/g
s/&zacute;/ź/g
s/&Zcaron;/Ž/g
s/&zcaron;/ž/g
s/&Zcy;/З/g
s/&zcy;/з/g
s/&Zdot;/Ż/g
s/&zdot;/ż/g
s/&zeetrf;/ℨ/g
s/&ZeroWidthSpace;/​/g
s/&Zeta;/Ζ/g
s/&zeta;/ζ/g
s/&Zfr;/ℨ/g
s/&ZHcy;/Ж/g
s/&zhcy;/ж/g
s/&zigrarr;/⇝/g
s/&Zopf;/ℤ/g
s/&zwj;/‍/g
s/&zwnj;/‌/g
